######################## default configuration ####################
baseURL = "/"
languageCode = "en-us"
title = "JInambou Japanese Food"
theme = "restaurant-hugo"
summaryLength = "10"
paginate = 4

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
URL = "css/bootstrap.min.css"
[[params.plugins.css]]
URL = "css/slick.css"
[[params.plugins.css]]
URL = "css/font-awesome.min.css"
[[params.plugins.css]]
URL = "css/animate.min.css"
[[params.plugins.css]]
URL = "css/venobox.css"
[[params.plugins.css]]
URL = "css/main.css"
[[params.plugins.css]]
URL = "css/responsive.css"

# JS Plugins
[[params.plugins.js]]
URL = "js/jquery.min.js"
[[params.plugins.js]]
URL = "js/bootstrap.min.js"
[[params.plugins.js]]
URL = "js/slick.min.js"
[[params.plugins.js]]
URL = "js/wow.min.js"
[[params.plugins.js]]
URL = "js/venobox.min.js"
[[params.plugins.js]]
URL = "js/main.js"

############################## navigation ###############################

[[menu.main]]
name = "Inicio"
URL = "hero-area"
weight = 1

[[menu.main]]
name = "Acerca de nosotros"
URL = "about-us"
weight = 2


[[menu.main]]
name = "Menu"
URL = "blog"
weight = 4

[[menu.main]]
name = "Novedades"
URL = "subscribe"
weight = 5

[[menu.main]]
name = "Contacto"
URL = "contact-us"
weight = 6


#################### default parameters ################################
[params]
logo = "images/logo2.png"
# meta data
author = "Themefisher"
description = "This is meta description"
# google analitycs ID
google_analitycs_id = "Your ID"
# mainSections
main_sections = ["post"]
# copyright
copyright = "Copyright 2020 - All Rights Reserved. Design and Developed By Themefisher.com"

# Preloader
[params.preloader]
enable = false
preloader = "" # use .png , .svg or .gif format

################################### Footer ############################
[params.footer]
enable = true
contactInfoTitle = "<span>CONTACTANOS</span> "
blogTitle = "Nuestro <span>MENU</span>"
galleryTitle = "PHOTO <span>STREAM</span>"
socialTitle = "<span>SIGUENOS</span>"

############################ footer contact item
[[params.footer.contactItem]]
title="Telefono"
icon = "fa fa-phone"
content = "+52(722)3275666 "

[[params.footer.contactItem]]
title="Direccion"
icon = "fa fa-map-marker"
content = "Avenida de los Castaños, Metepec 52148"

[[params.footer.socialLink]]
icon = "fa fa-map-marker"
link = "https://goo.gl/maps/u6KcQE5yrda9tj2D6"

[[params.footer.contactItem]]
title="E mail"
icon = "fa fa-envelope"
content = "jinambou2016@gmail.com"

######################### footer gallery
[[params.footer.gallery]]
image = "images/slider/platillo1.jpg"

[[params.footer.gallery]]
image = "images/slider/platillo2.jpg"

[[params.footer.gallery]]
image = "images/slider/platillo3.jpg"

[[params.footer.gallery]]
image = "images/slider/platillo4.jpg"

[[params.footer.gallery]]
image = "images/slider/platillo5.jpg"

[[params.footer.gallery]]
image = "images/slider/platillo6.jpg"

######################## Social Icon
[[params.footer.socialLink]]
icon = "facebook"
link = "https://www.facebook.com/jinamboucastanoazultec/"

[[params.footer.socialLink]]
icon = "twitter"
link = "https://twitter.com"

[[params.footer.socialLink]]
icon = "instagram"
link = "https://instagram.com/jinambou"
